- name: add PPA
  sudo: true
  apt_repository: repo=ppa:chris-lea/node.js
  register: result

- name: apt-get update
  sudo: true
  apt: update_cache=yes
  when: result.changed

- name: install package
  sudo: true
  apt: pkg=nodejs

- name: add `./node_modules/.bin` to PATH
  sudo: true
  copy: >
    src=nodejs_path.sh
    dest=/etc/profile.d/nodejs_path.sh
    mode=0644
  when: nodejs.add_node_modules_bin_to_path

- name: generate ~/.npmrc
  template: >
    src=npmrc.j2
    dest=~/.npmrc
    mode=0644
  when: nodejs.npmrc|length > 0
